package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/sougandhini/rssagg/internal/database"
)

func (apiCfg *apiConfig) handlerCreateUser(w http.ResponseWriter, r *http.Request) {
	// this is a standard function signature and this should never change but we still want out link to be passed here, so lets make it an api method then
	type parameters struct {
		Name string `json:"name"`
	}
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if params.Name == "" || params.Name == " " {
		responseWithError(w, 403, "Name field cannot be empty")
		return
	}
	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Error parsing request-JSON: %v", err))
		return
	}

	user, err := apiCfg.DB.CreateUser(r.Context(), database.CreateUserParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Name:      params.Name,
	}) // this method is generated by sqlc

	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Couldn't create user: %v", err))
		return
	}
	responseWithJSON(w, 201, databaseUserToResponseUser(user)) // now hook this up handler with a router
}

func (apiCfg *apiConfig) handlerGetUser(w http.ResponseWriter, r *http.Request, user database.User) {
	//endpoint which will only work for a logged-in user
	// apiKey, err := auth.GetAPIKey(r.Header)
	// if err != nil{
	// 	responseWithError(w, 403, fmt.Sprintf("Auth error: %v", err))
	// 	return
	// }

	// user, err := apiCfg.DB.GetUserByAPI(r.Context(), apiKey) //context package which gives way to track something that's happening across mutilple go routine, and we can also cancel the context - which kills http request
	// if err != nil{
	// 	responseWithError(w, 400, fmt.Sprintf("Could not get user: %v", err))
	// 	return
	// }

	//Note: we're replacing this in middleware, coz its required by multiple functions

	responseWithJSON(w, 200, databaseUserToResponseUser(user))
}
