package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/sougandhini/rssagg/internal/database"
)

func (apiCfg *apiConfig) handlerCreateFeed(w http.ResponseWriter, r *http.Request, user database.User) {
	// this is a standard function signature and this should never change but we still want out link to be passed here, so lets make it an api method then
	type parameters struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	}
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if (params.Name == "" || params.Name == " ") || (params.URL == "" || params.URL == " ") {
		responseWithError(w, 403, "name/url field cannot be empty")
		return
	}
	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Error parsing request-JSON: %v", err))
		return
	}

	feed, err := apiCfg.DB.CreateFeed(r.Context(), database.CreateFeedParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Name:      params.Name,
		Url:       params.URL,
		UserID:    user.ID, // we changed the last uuid foreign key reference to not null coz when it was by default set to nullUUID and we were getting error her coz of that
	}) // this method is generated by sqlc

	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Couldn't create feed: %v", err))
		return
	}
	responseWithJSON(w, 201, databaseFeedToFeed(feed)) // now hook this up handler with a router
}

func (apiCfg *apiConfig) handlerGetFeeds(w http.ResponseWriter, r *http.Request) {
	// this is a standard function signature and this should never change but we still want out link to be passed here, so lets make it an api method then

	feed, err := apiCfg.DB.GetFeeds(r.Context())
	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Couldn't get feeds: %v", err))
		return
	}
	responseWithJSON(w, 200, databaseFeedToFeeds(feed)) // now hook this up handler with a router
}

// func (apiCfg *apiConfig) handlerGetUser(w http.ResponseWriter, r *http.Request, user database.User) {
// 	responseWithJSON(w, 200, databaseUserToResponseUser(user))
// }
