package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/sougandhini/rssagg/internal/database"
)

func (apiCfg *apiConfig) handlerCreateFeedFollow(w http.ResponseWriter, r *http.Request, user database.User) {
	// this is a standard function signature and this should never change but we still want out link to be passed here, so lets make it an api method then
	type parameters struct {
		FeedID uuid.UUID `json:"feed_id"`
	}
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Error parsing request-JSON: %v", err))
		return
	}

	feedFollow, err := apiCfg.DB.CreateFeedFollow(r.Context(), database.CreateFeedFollowParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		UserID:    user.ID, // we changed the last uuid foreign key reference to not null coz when it was by default set to nullUUID and we were getting error her coz of that
		FeedID:    params.FeedID,
	}) // this method is generated by sqlc

	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Couldn't create feed-follow: %v", err))
		return
	}
	responseWithJSON(w, 201, databaseFeedToFeedFollows(feedFollow)) // now hook this up handler with a router
}

func (apiCfg *apiConfig) handlerGetFeedFollows(w http.ResponseWriter, r *http.Request, user database.User) {
	// this is a standard function signature and this should never change but we still want out link to be passed here, so lets make it an api method then

	feedFollow, err := apiCfg.DB.GetFeedFollows(r.Context(), user.ID)

	if err != nil {
		responseWithError(w, 400, fmt.Sprintf("Couldn't create feed-follow: %v", err))
		return
	}
	responseWithJSON(w, 200, databaseFeedFollowsToFeedFollows((feedFollow))) // now hook this up handler with a router
}
